appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: FKUFN4FYq9auAojhwa8nWsOMttLUAvYbMVJvKTYZ/WA7D9hlDw7KtQDAn7lLg/2U9DxI7nxgPkrsv7S8WaccRhB3GMB0isCf+VU2kHz5DNXwSQK5KeLeyGcch09KNchTdIyUEAENKanoL8IS7NYaTVWxq9wxVGAmTbZW0yYQKQx2vQKouCPIRJjtZlz64+eWuECYqdj8S3f1/BXvOFZvT8xxSs1UECz70So1ZGvX9X0rP165KZL64o42H5RXAcUvfCjW5ekjSX1gqaGCt5nvSIKvPNda2fc/tCUoWGo8vHLcvjqB96XF1fqnt8rsN8caHjHj9x5zqC511/WY7F/CuzkjokH42ubF7P6kmw6dGAMCfP9BiXJxOP5OB4P0Fuz2PXRtK1l+0tRmi2QqDY3QFbCXATdlrWSqcOoUT1DPk8SHgQ4THMWrtcunoctH3puhccNaYei/aJOwGTF8phW+GL7rCFKstJ0Lx11a4qR1U9gWzhzIEX9IFqtULCh417qQavuflXfd17wbwIH6Mj24JHzGNBUlUDHvyMjv0JFUN/MuKJAAOZMEYwMcuCs7Z/sSZf9j4oyjyAM44FHh/NzA66VM1Av9+dUHQP3l0M7Zm6gaLVxHTtYAcFTbXDb98xgX0YmaPBuf5gkn4bBkA0o4csllHXNw3+chCQJB1nPj7wc=
